\echo '--- 30 currencies ---'
INSERT INTO currency (code, name, decimal_places)
VALUES
  ('USD', 'US Dollar', 2),
  ('EUR', 'Euro', 2),
  ('GBP', 'Pound Sterling', 2),
  ('JPY', 'Japanese Yen', 0),
  ('CHF', 'Swiss Franc', 2),
  ('CAD', 'Canadian Dollar', 2),
  ('AUD', 'Australian Dollar', 2),
  ('NZD', 'New Zealand Dollar', 2),
  ('SEK', 'Swedish Krona', 2),
  ('NOK', 'Norwegian Krone', 2),
  ('DKK', 'Danish Krone', 2),
  ('HKD', 'Hong Kong Dollar', 2),
  ('SGD', 'Singapore Dollar', 2),
  ('ILS', 'Israeli New Shekel', 2),
  ('PLN', 'Polish Zloty', 2),
  ('CZK', 'Czech Koruna', 2),
  ('CNH', 'Offshore Chinese Yuan', 2),
  ('KRW', 'South Korean Won', 0),
  ('TWD', 'New Taiwan Dollar', 2),
  ('INR', 'Indian Rupee', 2),
  ('BRL', 'Brazilian Real', 2),
  ('MXN', 'Mexican Peso', 2),
  ('ZAR', 'South African Rand', 2),
  ('TRY', 'Turkish Lira', 2),
  ('THB', 'Thai Baht', 2),
  ('IDR', 'Indonesian Rupiah', 2),
  ('PHP', 'Philippine Peso', 2),
  ('HUF', 'Hungarian Forint', 2),
  ('RUB', 'Russian Ruble', 2),
  ('XAU', 'Gold', 4);

\echo '--- 60 exchanges ---'
INSERT INTO exchange (code, name)
VALUES
  ('XLDN', 'London Stock Exchange'),
  ('XFRK', 'Frankfurt Stock Exchange'),
  ('XNYK', 'New York Stock Exchange'),
  ('XSYD', 'Sydney Stock Exchange'),
  ('XTKY', 'Tokyo Stock Exchange'),
  ('XTOR', 'Toronto Stock Exchange'),
  ('XZRH', 'Zurich Stock Exchange'),
  ('XOSL', 'Oslo Stock Exchange'),
  ('XSTO', 'Stockholm Stock Exchange'),
  ('XCPH', 'Copenhagen Stock Exchange'),
  ('XAMS', 'Amsterdam Stock Exchange'),
  ('XBRU', 'Brussels Stock Exchange'),
  ('XLIS', 'Lisbon Stock Exchange'),
  ('XMAD', 'Madrid Stock Exchange'),
  ('XMIL', 'Milan Stock Exchange'),
  ('XVIE', 'Vienna Stock Exchange'),
  ('XWAW', 'Warsaw Stock Exchange'),
  ('XPRG', 'Prague Stock Exchange'),
  ('XBUD', 'Budapest Stock Exchange'),
  ('XHEL', 'Helsinki Stock Exchange'),
  ('XDUB', 'Dublin Stock Exchange'),
  ('XATH', 'Athens Stock Exchange'),
  ('XIST', 'Istanbul Stock Exchange'),
  ('XTLV', 'Tel Aviv Stock Exchange'),
  ('XBOM', 'Mumbai Stock Exchange'),
  ('XSIN', 'Singapore Stock Exchange'),
  ('XHKG', 'Hong Kong Stock Exchange'),
  ('XSEL', 'Seoul Stock Exchange'),
  ('XTPE', 'Taipei Stock Exchange'),
  ('XBKK', 'Bangkok Stock Exchange'),
  ('XJKT', 'Jakarta Stock Exchange'),
  ('XMNL', 'Manila Stock Exchange'),
  ('XKUL', 'Kuala Lumpur Stock Exchange'),
  ('XAKL', 'Auckland Stock Exchange'),
  ('XJNB', 'Johannesburg Stock Exchange'),
  ('XSAO', 'Sao Paulo Stock Exchange'),
  ('XBUE', 'Buenos Aires Stock Exchange'),
  ('XSCL', 'Santiago Stock Exchange'),
  ('XMEX', 'Mexico City Stock Exchange'),
  ('XYMQ', 'Montreal Stock Exchange'),
  ('XCHI', 'Chicago Stock Exchange'),
  ('XBOS', 'Boston Stock Exchange'),
  ('XSFO', 'San Francisco Stock Exchange'),
  ('XLAX', 'Los Angeles Stock Exchange'),
  ('XSEA', 'Seattle Stock Exchange'),
  ('XEDI', 'Edinburgh Stock Exchange'),
  ('XMAN', 'Manchester Stock Exchange'),
  ('XHAM', 'Hamburg Stock Exchange'),
  ('XMUC', 'Munich Stock Exchange'),
  ('XBER', 'Berlin Stock Exchange'),
  ('XPAR', 'Paris Stock Exchange'),
  ('XLYS', 'Lyon Stock Exchange'),
  ('XGVA', 'Geneva Stock Exchange'),
  ('XROM', 'Rome Stock Exchange'),
  ('XBCN', 'Barcelona Stock Exchange'),
  ('XOPO', 'Porto Stock Exchange'),
  ('XGOT', 'Gothenburg Stock Exchange'),
  ('XBGO', 'Bergen Stock Exchange'),
  ('XRIX', 'Riga Stock Exchange'),
  ('XTLL', 'Tallinn Stock Exchange');

\echo '--- 240 exchange rates ---'
\echo '    what one unit of each currency is worth in US dollars'
CREATE TEMP TABLE dollar_value (
  code char(3),
  worth_in_dollars numeric(20, 10)
);

INSERT INTO dollar_value (code, worth_in_dollars)
VALUES
  ('USD', 1.0),
  ('EUR', 1.1542),
  ('GBP', 1.3467),
  ('JPY', 0.006336),
  ('CHF', 1.2382),
  ('CAD', 0.7300),
  ('AUD', 0.6628),
  ('NZD', 0.6063),
  ('SEK', 0.1063),
  ('NOK', 0.1015),
  ('DKK', 0.1546),
  ('HKD', 0.1275),
  ('SGD', 0.7810),
  ('ILS', 0.2960),
  ('PLN', 0.2725),
  ('CZK', 0.0477),
  ('CNH', 0.1389),
  ('KRW', 0.000702),
  ('TWD', 0.0317),
  ('INR', 0.0114),
  ('BRL', 0.1830),
  ('MXN', 0.0545),
  ('ZAR', 0.0560),
  ('TRY', 0.0248),
  ('THB', 0.0284),
  ('IDR', 0.0000612),
  ('PHP', 0.0172),
  ('HUF', 0.0029),
  ('RUB', 0.0111),
  ('XAU', 2400.0);

INSERT INTO fx_rate (from_currency, to_currency, rate, rate_date, where_from)
SELECT
  one.code,
  other.code,
  one.worth_in_dollars / other.worth_in_dollars,
  CURRENT_DATE,
  'STARTING VALUE'
FROM
  dollar_value AS one,
  dollar_value AS other
WHERE
  other.code IN ('USD', 'EUR', 'GBP', 'JPY', 'CHF', 'CAD', 'AUD', 'NZD');
