server:
  ssl:
    enabled: true
    bundle: gateway

spring:
  ssl:
    bundle:
      jks:
        gateway:
          key:
            alias: ${TLS_KEY_ALIAS:gateway}
          keystore:
            location: ${TLS_KEYSTORE_LOCATION}
            password: ${TLS_KEYSTORE_PASSWORD}
            type: PKCS12
          truststore:
            location: ${TLS_TRUSTSTORE_LOCATION}
            password: ${TLS_TRUSTSTORE_PASSWORD}
            type: PKCS12

management:
  endpoint:
    health:
      show-details: never
